### ISSUE TITLE
policy workflow to use main branch

### ISSUE THREAD

**Issue by roneli** [cloudquery/.github#126]
### Describe the bug

providers policy test validation, only runs on latest version, if there is a breaking change we require to tag before those tests can pass, moreover we might miss bugs in latest.

### Expected Behavior

pull latest core version instead of latest tag

### Steps to Reproduce

-

### Provider and CloudQuery version

main

**Comment by disq** [comment]
I think we should have 2 workflows, one for prov PR+cq-core main (to test tip) and one for prov PR+cq-core latest release (to test backwards compatibility)

**Comment by erezrokah** [comment]
With all the recent policy changes I think we can close this. Please re-open if relevant
