### ISSUE TITLE
.golangci.yml dec-order controverses cq-gen generation order

### ISSUE THREAD

**Issue by amanenk** [cloudquery/.github#266]
### Describe the bug

cq-gen generates user defined funcitons and types under  `User Defined Helpers` at the end of the file. 
dec-order in linter configuration required types to be above functions

### Expected Behavior

cq-gen should generate code acording to `dec-order` bloc or `dec-order` should be disabled.

### Steps to Reproduce

generate file with user type and funtion and run golangci-lint

### Provider and CloudQuery version

-

**Comment by hermanschaaf** [comment]
My workaround to this has been to declare types inside the functions that need them. This won't work for everything, but it might work in many cases.

**Comment by erezrokah** [comment]
I think we can close this due to https://github.com/cloudquery/cloudquery/pull/1184.
We can discuss in the future if we want to spend time on ensuring cq-gen and all of our linting rules are aligned.
Please re-open if I got this wrong
